name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  # Check whether to build the wheels and the source tarball
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
