name: Test workflow

on:
  push:
    branches:
      - main

jobs:
  # Check whether to build the wheels and the source tarball
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: cibuildwheel
        uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a # v2.23.2
      - name: cibuildwheel with previous release commit hash
        uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a # v2.23.2
      - name: cibuildwheel with previous release
        uses: pypa/cibuildwheel@v2.23.2
      - name: cibuildwheel with wrong comment this is actually 2.23.1
        uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a # v2.23.0

  test-with-wrong-commit-hash:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: cibuildwheel with wrong commit hash this is from development branch
        uses: pypa/cibuildwheel@d04cacbc9866d432033b1d09142936e6a0e2121a # v2.23.2
